import 'package:flutter/material.dart';
import '../../core/app_state.dart';
import '../../core/models.dart';
import '../../widgets/common.dart';

class GoalsPage extends StatelessWidget { const GoalsPage({super.key}); @override Widget build(BuildContext context){final s=AppStateScope.of(context);return Scaffold(appBar:AppBar(title:const Text('目標',style:TextStyle(fontWeight:FontWeight.w800))),body:PageWrap(child:ListView(padding:const EdgeInsets.fromLTRB(16,8,16,100),children:[const SectionTitle('ACTIVE GOALS'),for(final g in s.goals.where((x)=>x.status==GoalStatus.active))Card(child:ListTile(onTap:()=>_detail(context,g),title:Text(g.title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:8),LinearProgressIndicator(value:g.progress),const SizedBox(height:6),Text('${(g.progress*100).round()}%  ·  ${g.deadline}')]),trailing:const Icon(Icons.chevron_right))) ])));}
 Future<void> _detail(BuildContext context,GoalItem g)=>showModalBottomSheet<void>(context:context,isScrollControlled:true,showDragHandle:true,builder:(c)=>_GoalDetail(goal:g)); }
class _GoalDetail extends StatelessWidget { const _GoalDetail({required this.goal}); final GoalItem goal; @override Widget build(BuildContext context){final s=AppStateScope.of(context);final ms=s.milestones.where((m)=>m.goalId==goal.id).toList();return SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(24,4,24,32),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(goal.title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800))),IconButton(onPressed:()=>_editGoal(context,s),icon:const Icon(Icons.edit_outlined))]),Text(goal.deadline),const SizedBox(height:16),LinearProgressIndicator(value:goal.progress,minHeight:8),const SizedBox(height:6),Text('${(goal.progress*100).round()}%'),if(goal.why.isNotEmpty)...[const SizedBox(height:20),const Text('なぜ？',style:TextStyle(fontWeight:FontWeight.w700)),Text(goal.why)],const SizedBox(height:20),const Text('MILESTONES',style:TextStyle(fontWeight:FontWeight.w700)),for(final m in ms)ListTile(contentPadding:EdgeInsets.zero,title:Text(m.title),subtitle:LinearProgressIndicator(value:m.progress),trailing:Text('${(m.progress*100).round()}%')),TextButton.icon(onPressed:()=>_addMilestone(context,s),icon:const Icon(Icons.add),label:const Text('マイルストーンを追加')),if(goal.nextAction.isNotEmpty)...[const SizedBox(height:12),const Text('NEXT ACTION',style:TextStyle(fontWeight:FontWeight.w700)),Text(goal.nextAction)] ])));}
 Future<void> _addMilestone(BuildContext context,AppState s)async{final c=TextEditingController();await showDialog<void>(context:context,builder:(d)=>AlertDialog(title:const Text('マイルストーンを追加'),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(labelText:'タイトル')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('キャンセル')),FilledButton(onPressed:(){if(c.text.trim().isNotEmpty)s.addMilestone(goal.id,c.text.trim());Navigator.pop(d);},child:const Text('追加'))]));c.dispose();}
 Future<void> _editGoal(BuildContext context,AppState s)async{final t=TextEditingController(text:goal.title);final dline=TextEditingController(text:goal.deadline);final why=TextEditingController(text:goal.why);final next=TextEditingController(text:goal.nextAction);var progress=goal.progress;await showDialog<void>(context:context,builder:(d)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:const Text('目標を編集'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'目標')),TextField(controller:dline,decoration:const InputDecoration(labelText:'期限')),TextField(controller:why,decoration:const InputDecoration(labelText:'なぜ？')),TextField(controller:next,decoration:const InputDecoration(labelText:'次の行動')),const SizedBox(height:12),Text('進捗 ${(progress*100).round()}%'),Slider(value:progress,onChanged:(v)=>setLocal(()=>progress=v))])),actions:[TextButton(onPressed:(){s.deleteGoal(goal);Navigator.pop(d);Navigator.pop(context);},child:const Text('削除')),FilledButton(onPressed:(){goal.title=t.text.trim();goal.deadline=dline.text.trim();goal.why=why.text.trim();goal.nextAction=next.text.trim();goal.progress=progress;s.updateGoal(goal);Navigator.pop(d);},child:const Text('保存'))])));t.dispose();dline.dispose();why.dispose();next.dispose();}
}
