import 'package:flutter/material.dart';
import '../../core/app_state.dart';
import '../../core/models.dart';

Future<void> editTask(BuildContext context, MemoryTask task) async { final s=AppStateScope.of(context); final c=TextEditingController(text:task.title); var bucket=task.bucket; await showDialog<void>(context:context,builder:(d)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:const Text('やることを編集'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:c,autofocus:true,decoration:const InputDecoration(labelText:'タイトル')),const SizedBox(height:12),DropdownButtonFormField<TaskBucket>(initialValue:bucket,items:TaskBucket.values.map((e)=>DropdownMenuItem(value:e,child:Text(_bucket(e)))).toList(),onChanged:(v)=>setLocal(()=>bucket=v!))]),actions:[TextButton(onPressed:(){s.deleteTask(task);Navigator.pop(d);},child:const Text('削除')),FilledButton(onPressed:(){if(c.text.trim().isNotEmpty){task.title=c.text.trim();task.bucket=bucket;s.updateTask(task);}Navigator.pop(d);},child:const Text('保存'))]))); c.dispose(); }
String _bucket(TaskBucket b)=>switch(b){TaskBucket.inbox=>'Inbox',TaskBucket.today=>'今日',TaskBucket.soon=>'近いうち',TaskBucket.someday=>'いつか'};

Future<void> editWant(BuildContext context, WantItem item) async { final s=AppStateScope.of(context); final title=TextEditingController(text:item.title); final waiting=TextEditingController(text:item.waitingFor); var status=item.status; await showDialog<void>(context:context,builder:(d)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:const Text('買いたいを編集'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'名前')),const SizedBox(height:12),TextField(controller:waiting,decoration:const InputDecoration(labelText:'待機条件')),const SizedBox(height:12),DropdownButtonFormField<WantStatus>(initialValue:status,items:WantStatus.values.map((e)=>DropdownMenuItem(value:e,child:Text(e.name))).toList(),onChanged:(v)=>setLocal(()=>status=v!))]),actions:[TextButton(onPressed:(){s.deleteWant(item);Navigator.pop(d);},child:const Text('削除')),FilledButton(onPressed:(){if(title.text.trim().isNotEmpty){item.title=title.text.trim();item.waitingFor=waiting.text.trim();item.status=status;s.updateWant(item);}Navigator.pop(d);},child:const Text('保存'))]))); title.dispose(); waiting.dispose(); }

Future<void> editFuture(BuildContext context, FutureItem item) async { final s=AppStateScope.of(context); final title=TextEditingController(text:item.title); final timing=TextEditingController(text:item.timing); var status=item.status; await showDialog<void>(context:context,builder:(d)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:const Text('予定候補を編集'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'予定')),const SizedBox(height:12),TextField(controller:timing,decoration:const InputDecoration(labelText:'時期 例：11月 / 冬 / 来年')),const SizedBox(height:12),DropdownButtonFormField<FutureStatus>(initialValue:status,items:FutureStatus.values.map((e)=>DropdownMenuItem(value:e,child:Text(e.name))).toList(),onChanged:(v)=>setLocal(()=>status=v!))]),actions:[TextButton(onPressed:(){s.deleteFuture(item);Navigator.pop(d);},child:const Text('削除')),FilledButton(onPressed:(){if(title.text.trim().isNotEmpty){item.title=title.text.trim();item.timing=timing.text.trim();item.status=status;s.updateFuture(item);}Navigator.pop(d);},child:const Text('保存'))]))); title.dispose(); timing.dispose(); }
